## APP SETTINGS
# AZURE CONNECTION STRING
QUEUE_CONNECTION = ""
# QUEUE NAME
QUEUE_NAME = ""
# SCRIPT FILENAME
SCRIPT_FILENAME = "./test_script.sh"

## PROOF №1 - NEGATIVE(!) CHECKING CONTENT MESSAGE
# NEEDLE FOR IN QUEUE MESSAGING
PROOF1_CONTENT_MESSAGE = "slot=A"

## PROOF №2 - CHECK ENVIRONMENT
# URL CONTAINS isAlive 'Env' data
PROOF2_URL = ""
# NEEDLE FOR SEARCH IN CONTENT
PROOF2_ENVIRONMENT = "slot=B"
